logging:
  level:
    org.springframework.web: ERROR
    org.springframework.security: ERROR
    com.zthulj: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /tmp/zThulj_blog.log
  security.encoding-strength: 256
jwt.signingkey: MayTheForceBeWithYou
http.realmname: ThisIsTheRealName

image.static.path: "/Users/zjeremy/Documents/test/"
spring:
  servlet:
    multipart:
      max-file-size: 2048KB
      max-request-size: 2048KB
  multipart.enabled: false
twitter:
  consumer.key:
  consumer.secret:
  access.token: -
  token.secret:

host: http://localhost:8081
